### PR TITLE
[SUPPORTESC-183] update valid polling intervals

### PR DESCRIPTION
**Pull request by armchairlinguist**
Just keeping us honest here, as per https://zapier.com/pricing. 😄

### CODE REVIEW

**Review by xavdid — DISMISSED** [review]
This is good as is, but I might make it more generic so we don't have to keep updating it as our plans change: 

> Live Zaps automatically poll the URL for new data every few minutes; the exact interval depends on the user's Zapier plan (see [Plans](https://zapier.com/pricing))

**Comment by armchairlinguist** [comment]
That's a good idea! Although since the currently available plans do change from time to time, I wonder about it potentially causing confusion. Any thoughts there?

**Comment by xavdid** [comment]
We don't have to link to pricing at all, I just figured it would give a helpful, evergreen list of the rough polling intervals. IMO I don't think the exact number of minutes here matters a ton.

**Comment by armchairlinguist** [comment]
@xavdid Thanks for the thoughts! I went with a hybrid approach (info and link) for now. I have seen cases where the specifics are important for certain APIs/customer use cases, so hopefully this is a good balance.

**Review by xavdid — APPROVED** [review]
cool, thanks!

**Pull request merged**
