### PR TITLE
PDE-1820: Example CLI apps anchor link is dead

### PR DESCRIPTION
**Pull request by kgodtfredsen**
I'm not sure where this used to go - was it this page, or did we render that page as an anchor somewhere?

### CODE REVIEW

**Review by xavdid — APPROVED** [review]
yeah, must have been a removed anchor

**Comment by kgodtfredsen** [comment]
https://zapierorg.atlassian.net/browse/PDE-1820

**Comment by kgodtfredsen** [comment]
@xavdid - I had to create a Jira ticket for it, so if you could re-review, hopefully that gets it processed.

**Review by xavdid — APPROVED** [review]
all good! 

I believe you need to add the tag to the PR title, but it shouldn't require a re-review.

**Pull request merged**
