### PR TITLE
[SUPPORTESC-199] Update and move REST Hook FAQ content to Triggers page

### PR DESCRIPTION
**Pull request by armchairlinguist**
* Remove embedded tester details from REST Hooks FAQ (the tester is no longer available for REST Hooks)
* Since that shortens the FAQ content quite a bit, merge it with the regular REST Hooks content and clean up the result
* Leave a stub in case people have existing links to that section

Might need to add the original FAQ title anchor in the stub too? I didn't see any other internal links using it, though.

### CODE REVIEW

**Review by xavdid — COMMENTED** [review]
This looks good, but you may want to touch base with @ZaneLyon on https://github.com/zapier/visual-builder/pull/230 - looks like y'all are working on the same doc!

**Comment by armchairlinguist** [comment]
You're so right, thanks for highlighting that! I commented there just now.

**Comment by armchairlinguist** [comment]
@xavdid Based on @ZaneLyon 's [comment in his PR](https://github.com/zapier/visual-builder/pull/230#issuecomment-923596018), would you be willing to approve mine?

**Review by xavdid — APPROVED** [review]
looks great!

**Pull request merged**
