### PR TITLE
PLATSUPP-988 Docs Overhaul Project Updates

### PR DESCRIPTION
**Pull request by marinahand**

### CODE REVIEW

**Comment by justin-lee-zapier** [comment]
When you're ready for @team-platform-support to review this, please head over to this [Slack thread](https://zapier.slack.com/archives/C02PCUNBUG7/p1699447182925339) and give us a `:review-pr:` emoji.

**Comment by marinahand** [comment]
:fyi: the content here has been peer reviewed as part of [#wg-overhaul-platform-docs](https://zapier.slack.com/archives/C0278AQTXT4) - so just looking for a final check of format to push this live.

**Review by justin-lee-zapier — APPROVED** [review]
This looks good to me, I'll approve.

**Review by justin-lee-zapier — APPROVED** [review]
New spacing looks good.

**Pull request merged**
