### PR TITLE
PLATSUP-1048_subdomain_validation

### PR DESCRIPTION
**Pull request by marinahand**
-Add content for subdomain validation
-Link mentions of subdomain in auth docs to the new content

### CODE REVIEW

**Comment by justin-lee-zapier** [comment]
When you're ready for @team-platform-support to review this, please head over to this [Slack thread](https://zapier.slack.com/archives/C02PCUNBUG7/p1717607024973709) and give us a `:review-pr:` emoji.

**Comment by marinahand** [comment]
Waiting on feedback here before asking for approval: https://zapier.slack.com/archives/C075FN7NX46/p1717607042584209?thread_ts=1717071420.139339&cid=C075FN7NX46

**Review by rnegron — COMMENTED** [review]
@marinahand Thank you so much for getting these changes up! I left some copy suggestions 🙏🏻 let me know if they make sense!

**Comment by marinahand** [comment]
@rnegron looks great, I committed all of them, TY!

**Review by rnegron — APPROVED** [review]

**Pull request merged**
